anchor_version = "0.24.2"
solana_version = "1.9.13"

[scripts]
test = "yarn mocha tests/*.spec.ts"

[provider]
cluster = "devnet"
wallet = "~/deployments/cryptocoders/cardinal/upgrade_authority.json" #BoznqR4hpJ4BnN1qeGhLbVpFZFKccBDKbtFDyx2tooCo

[programs.mainnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'pmvYY6Wgvpe3DEj3UX1FcRpMx43sMLYLJrFTVGcqpdn'

[programs.devnet]
cardinal_token_manager = "H7h6dv6X9KGLuCFvYMNa1zmCP5VCSzw8AkQGod6zaCnX"
#cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'pmvYY6Wgvpe3DEj3UX1FcRpMx43sMLYLJrFTVGcqpdn'

[programs.testnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'pmvYY6Wgvpe3DEj3UX1FcRpMx43sMLYLJrFTVGcqpdn'

[programs.localnet]
cardinal_token_manager = "mgr99QFMYByTqGPWmNqunV7vBLmWWXdSrHUfV8Jf3JM"
cardinal_paid_claim_approver = "pcaBwhJ1YHp7UDA7HASpQsRUmUNwzgYaLQto2kSj1fR"
cardinal_time_invalidator = "tmeEDp1RgoDtZFtx6qod3HkbQmv9LMe36uqKVvsLTDE"
cardinal_use_invalidator = "useZ65tbyvWpdYCLDJaegGK34Lnsi8S3jZdwx8122qp"
cardinal_payment_manager = 'pmvYY6Wgvpe3DEj3UX1FcRpMx43sMLYLJrFTVGcqpdn'
